### ISSUE TITLE
Build fails with unbounded module error

### ISSUE THREAD

**Issue by foollbar** [DistributedComponents/verdi-runtime#13]
I've been following https://github.com/uwplse/verdi#Building instructions but command <pre> opam install verdi-runtime </pre> failed with a following error message.

<pre>
<><> Processing actions <><><><><><><><><><><><><><><><><><><><><><><><><><>  🐫
[ERROR] The compilation of verdi-runtime failed at
        "/Users/user/.opam/opam-init/hooks/sandbox.sh build ocaml pkg/pkg.ml build
        --pinned false".

#=== ERROR while compiling verdi-runtime.dev ==================================#
# context     2.0.3 | macos/x86_64 | ocaml-base-compiler.4.07.1 | http://opam-dev.distributedcomponents.net
# path        ~/.opam/default/.opam-switch/build/verdi-runtime.dev
# command     ~/.opam/opam-init/hooks/sandbox.sh build ocaml pkg/pkg.ml build --pinned false
# exit-code   1
# env-file    ~/.opam/log/verdi-runtime-13459-a71bb4.env
# output-file ~/.opam/log/verdi-runtime-13459-a71bb4.out
### output ###
# [...]
# ocamlfind ocamlopt -c -g -bin-annot -safe-string -package cheerios-runtime -package yojson -package ppx_deriving_yojson -package base64 -I src -o src/DebugShim.cmx src/DebugShim.ml
# + ocamlfind ocamlopt -c -g -bin-annot -safe-string -package cheerios-runtime -package yojson -package ppx_deriving_yojson -package base64 -I src -o src/DebugShim.cmx src/DebugShim.ml
# File "src/DebugShim.ml", line 100, characters 28-38:
# Error: Unbound module B64
# Command exited with code 2.
# pkg.ml: [ERROR] cmd ['ocamlbuild' '-use-ocamlfind' '-classic-display' '-j' '4' '-tag' 'debug'
#      '-build-dir' '_build' 'opam' 'pkg/META' 'CHANGES.md' 'LICENSE.md'
#      'README.md' 'src/Util.cmi' 'src/Opts.cmi' 'src/Daemon.cmi'
#      'src/Shim.cmi' 'src/DisklessShim.cmi' 'src/OrderedShim.cmi'
#      'src/UnorderedShim.cmi' 'src/DynamicShim.cmi' 'src/DiskOpShim.cmi'
#      'src/DebugShim.cmi' 'src/verdi_runtime.a' 'src/verdi_runtime.cma'
#      'src/verdi_runtime.cmxa' 'src/verdi_runtime.cmxs']: exited with 10

<><> Error report <><><><><><><><><><><><><><><><><><><><><><><><><><><><><>  🐫
┌─ The following actions failed
│ λ build verdi-runtime dev
└─
╶─ No changes have been performe
</pre>

is there any quick fix I can apply?

**Comment by palmskog** [comment]
This is due to a recent API-breaking change in the base64 OCaml package. If you use a version of base64 below 3.0.0, it will work. I'll update the relevant `opam` files for verdi-runtime.
